### ISSUE TITLE
Need help with travis

### ISSUE THREAD

**Issue by kajo404** [Rostlab/JS16_ProjectE#21] opened 2016-03-25 18:25 UTC
Hey Guys our Project E representative is not available over the holidays and I was hoping maybe someone else from this team can help us.

I have no idea why our build is failing. Can someone have a look at this please
https://travis-ci.org/Rostlab/JS16_ProjectD_Group5/builds/118503829

**Comment by jsalahov** [comment] 2016-03-25 19:46
Hmm. The error happened during 'git checkout' which means your code is fine. And the main branch passes the build, so the problem is only with this pull request. And the reason of that error (the one that I know of) is something got deleted in remote repo, like the branch or commit got lost etc. It can also be a sync problem between github and travis.
Investigating...
Meanwhile, as I said there is nothing _wrong_ with your code, so keep working :smiley:

**Comment by jsalahov** [comment] 2016-03-25 21:07
@kajo404 There are odd things happening in your repo :smile: Sometimes you merge 'feature branch' to 'develop' and other time vice versa. See [here](https://github.com/Rostlab/JS16_ProjectD_Group5/network) While it is not strictly illegal, you might want to keep it consistent with your workflow. One case of that behaviour seems to mess up (I think that is the likely cause) your pull request. I mean this [merge](https://github.com/Rostlab/JS16_ProjectD_Group5/commit/2e77e6f12f45a8b7453e89312b081ba59cd79ee8) and this [merge](https://github.com/Rostlab/JS16_ProjectD_Group5/commit/b298982a92ebaaf64521b52487aa73708c50c260)

**Comment by kajo404** [comment] 2016-03-25 22:24
So what i am doing when somebody else merges a pull request to develop is `git pull origin develop` to get the changes to my branch. Have I been doing something terribly wrong?

**Comment by jsalahov** [comment] 2016-03-26 08:57
@kajo404 I meant "you" as a team. There is nothing wrong with that command. But see your repo's commit history. It first starts here: 
See the first occurence of "Merged branch 'develop' into ..." : 
https://github.com/Rostlab/JS16_ProjectD_Group5/commits/develop?page=8
After that  mergefest begins :smile: You (again as a team) have been merging your branches to branches, then merge those merges to merges and all sorts of other jolly activities :smile: 
Somewhere down the line ( or maybe just recently) that resulted in history being overwritten. That's why travis can't find the ref for pull request.

**Comment by jsalahov** [comment] 2016-03-26 09:00
And as for the solution, thankfully, your repo seems to be converged on branch 'develop' now. So in the future try to be consistent: branch from the 'develop' and merge into the 'develop'
This reference may come in handy:
https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow

**Closed as completed by jsalahov** 2016-03-26 09:00 UTC

**Comment by jcebel** [comment] 2016-03-28 21:10
thanks @CavidSalahov!
